#####################################################################################################
# “PrOMMiS” was produced under the DOE Process Optimization and Modeling for Minerals Sustainability
# (“PrOMMiS”) initiative, and is copyright (c) 2023-2026 by the software owners: The Regents of the
# University of California, through Lawrence Berkeley National Laboratory, et al. All rights reserved.
# Please see the files COPYRIGHT.md and LICENSE.md for full copyright and license information.
#####################################################################################################
r"""
Settler Tank Model

========================

Author: Douglas Allan

The SettlerTank unit model represents the settler tank portion of the mixer-settler unit operation.
In the settler tank, two phases of different densities separate. The light phase overflows the top
of the tank via a weir. The method by which the heavy tank is unspecified, because there are
multiple mixer-settler configurations in which the heavy phase leaves in different ways (such as
overflowing a second weir, being pumped out of the bottom of the tank, or leaving the bottom of the
tank by the suction generated by the next mixer-settler's impeller.)

Configuration Arguments
-----------------------

- ``has_holdup``: The SettlerTank always has holdup, so this option must equal True.
- ``dynamic``: Boolean determining whether to create a dynamic or steady state model.
- ``light_phase_alias``: String to use as an alias for the light phase. For example, if
    the user has ``light_phase_alias = "organic"``, the ``organic_phase`` attribute will be
    created as a reference to the ``light_phase`` control volume, and the ``organic_inlet``
    and ``organic_outlet`` ports will be created.
- ``heavy_phase_alias``: String to use as an alias for the heavy phase. For example, if
    the user has ``heavy_phase_alias = "aqueous"``, the ``aqueous_phase`` attribute will be
    created as a reference to the ``heavy_phase`` control volume, and the ``aqueous_inlet``
    and ``aqueous_outlet`` ports will be created.
- ``light_phase_config``: Configuration dictionary for the light phase, described below.
- ``heavy_phase_config``: Configuration dictionary for the heavy phase, described below.
- ``transformation_method``: PyomoDAE transformation method for the ``ControlVolume1D`` objects.
- ``transformation_scheme``: PyomoDAE transformation scheme for the ``ControlVolume1D`` objects.
- ``finite_elements``: Number of finite elements to use when discretizing the ``ControlVolume1D``
    objects
- ``collocation_points``: Number of collocation points to use if a collocation method is used
    to discretize the ``ControlVolume1D`` objects.

Stream configurations
---------------------

Both phases are configured using a configuration dictionary.

- ``property_package``: The ``PhysicalParameterBlock``used for the stream's properties.

- ``property_package_args``: Configuration arguments used when creating the stream's ``StateBlock``
    objects.
- ``energy_balance_type``: Which energy balance type, if any, that should be created. The permitted
    options are ``EnergyBalanceType.none``, ``EnergyBalanceType.enthalpyTotal``,
    ``EnergyBalanceType.energyTotal``, and ``EnergyBalanceType.isothermal``. The default value
    is ``EnergyBalanceType.none``.
- ``has_pressure_balance``: Boolean determining whether or not to create pressure balance equations.

Degrees of freedom
------------------
In addition to the variables on the inlet ports, it is expect that the user will specify the
following variables:
- ``length``: The length of the settler tank parallel with the flow
- ``settler_width``: The width of the settler tank perpendicular to the flow
- ``light_phase_weir_channel_width``: The width of the weir through which the light phase drains.
    This is usually the same as the ``settler_width``.
- ``light_phase_weir_height``: The height of the light phase weir measured from the bottom of the
    settler tank.

When the system is at steady state, the user must also specify *exactly* one of the following variables:
- ``light_phase_height``: The height of the light phase measured from the top of the heavy phase.
- ``heavy_phase_height``: The height of the heavy phase measured from the bottom of the settler tank.

Model structure
---------------

In this unit model, the two phases are represented by parallel ControlVolume1D objects. There is
no material transfer between them because it is assumed that all material transfer occurred in the
mixer portion. Each phase takes up a certain height within the tank, and the difference between
the top of the light phase and the light phase weir's height is the driving force for the flow
of the light phase out of the tank. The weir flow relationship is taken from [1]. When the total
liquid height of the tank is less than that of the light phase weir's height, there is zero
flow out of the tank.

Additional Parameters
---------------------

The model has the following parameters:

- ``weir_discharge_coefficient``: The dimensionless discharge coefficient used for weir flow.
    The default value of 0.583 is taken from [1].
- ``weir_flow_smoothing_eps``: A parameter used in ``smooth_max`` to smooth the transition
    between nonzero flow when the liquid height is greater than the tank's height and zero
    flow when the liquid height is less than the tank's height. It has a default value of 1 μm.

Additional Constraints
----------------------

In addition to the constraints generated within the `ControlVolume1D` objects, the unit model
has the following constraints:
- Geometric constraints:
  - ``length_eqn``: A constraint setting the light phase's flow length equal to the heavy
    phase's length.
  - ``light_phase_area_eqn``: A constraint setting the light phase's flow area equal to the
    product of the light phase's height and the settler width.
  - ``heavy_phase_area_eqn``: A constraint setting the heavy phase's flow area equal to the
    product of the heavy phase's height and the settler width.
- Performance Constraint:
  - ``weir_flow_eqn``: A constraint defining the light phase's outlet flow in terms of the
    height of the light phase over the weir.

Additional Expressions
----------------------
The following unit model level expression is created:
- ``total_liquid_height``: The sum of the light phase's and heavy phase's heights.

Bibliography
------------

[1] Vanden-Broeck, J. M., & Keller, J. B. (1987). Weir flows. Journal of fluid mechanics, 176, 283-293.
"""

from pyomo.common.config import Bool, ConfigDict, ConfigValue, In
from pyomo.environ import (
    Block,
    ComponentMap,
    Param,
    units as pyunits,
    value,
    Var,
)
from pyomo.util.calc_var_value import calculate_variable_from_constraint
from idaes.core import (
    declare_process_block_class,
    DistributedVars,
    EnergyBalanceType,
    ExtendedControlVolume1DBlock,
    FlowDirection,
    MaterialBalanceType,
    MomentumBalanceType,
    UnitModelBlockData,
    useDefault,
)
from idaes.core.initialization import (
    SingleControlVolumeUnitInitializer,
)
from idaes.core.scaling import CustomScalerBase, DefaultScalingRecommendation
from idaes.core.util.constants import Constants
from idaes.core.util.config import DefaultBool, is_physical_parameter_block
from idaes.core.util.exceptions import (
    BurntToast,
    ConfigurationError,
    InitializationError,
)
from idaes.core.util.math import smooth_max
from idaes.core.util.misc import add_object_reference
from idaes.core.util.model_statistics import degrees_of_freedom

import idaes.logger as idaeslog


class SettlerTankScaler(CustomScalerBase):
    """
    Default scaler object for the SettlerTank unit model.
    """

    DEFAULT_SCALING_FACTORS = {
        # Assume that the other tank dimensions have the same scale as the tank length
        "length": DefaultScalingRecommendation.userInputRecommended,
        # The weir width could be an order of magnitude smaller than the tank length,
        # depending on how the tank is set up.
        "light_phase_weir_channel_width": DefaultScalingRecommendation.userInputRecommended,
    }

    def variable_scaling_routine(
        self, model, overwrite: bool = False, submodel_scalers: ComponentMap = None
    ):
        """
        Variable scaling routine for the SettlerTank unit model.

        Args:
            model: instance of SettlerTank to be scaled
            overwrite: whether to overwrite existing scaling factors
            submodel_scalers: dict of Scalers to use for sub-models, keyed by submodel local name

        Returns:
            None
        """
        ############################################################################################################
        ## Step 1: Scale geometric variables
        ############################################################################################################
        self.scale_variable_by_default(model.length, overwrite=overwrite)
        sf_L = self.get_scaling_factor(model.length)
        if sf_L is None:
            L = value(model.length)
            if L > 0:
                sf_L = 1 / L
                self.set_variable_scaling_factor(
                    model.length, sf_L, overwrite=overwrite
                )
            else:
                raise RuntimeError(
                    "The variable SettlerTank.length should be strictly positive, but "
                    f"instead it has a value of {L}."
                )
        # Use definition equation in case light and heavy phase have different units
        self.scale_variable_by_definition_constraint(
            model.heavy_phase.length, model.length_eqn, overwrite=overwrite
        )

        self.set_variable_scaling_factor(model.settler_width, sf_L, overwrite=overwrite)
        self.set_variable_scaling_factor(
            model.light_phase_weir_height, sf_L, overwrite=overwrite
        )
        for t in model.flowsheet().time:
            self.set_variable_scaling_factor(
                model.light_phase_height[t], sf_L, overwrite=overwrite
            )
            self.set_variable_scaling_factor(
                model.heavy_phase_height[t], sf_L, overwrite=overwrite
            )

        self.scale_variable_by_default(
            model.light_phase_weir_channel_width, overwrite=overwrite
        )
        if self.get_scaling_factor(model.light_phase_weir_channel_width) is None:
            self.set_variable_scaling_factor(
                model.light_phase_weir_channel_width, sf_L, overwrite=overwrite
            )

        for phase in ["light", "heavy"]:
            control_volume = getattr(model, f"{phase}_phase")
            constraint = getattr(model, f"{phase}_phase_area_eqn")
            for idx, vardata in control_volume.area.items():
                self.scale_variable_by_definition_constraint(
                    vardata, constraint[idx], overwrite=overwrite
                )

        ############################################################################################################
        ## Step 2: Call control volumes' variable scaling routines
        ############################################################################################################
        self.call_submodel_scaler_method(
            model.light_phase,
            "variable_scaling_routine",
            submodel_scalers=submodel_scalers,
            overwrite=overwrite,
        )
        self.call_submodel_scaler_method(
            model.heavy_phase,
            "variable_scaling_routine",
            submodel_scalers=submodel_scalers,
            overwrite=overwrite,
        )
        ############################################################################################################
        ## Step 3: Scale performance variables
        ############################################################################################################
        # There are no performance variables, so we are done.

    def constraint_scaling_routine(
        self, model, overwrite: Bool = False, submodel_scalers: ComponentMap = None
    ):
        """
        Routine to apply scaling factors to constraints in the SettlerTank unit model.

        Args:
            model: SettlerTank to be scaled
            overwrite: whether to overwrite existing scaling factors
            submodel_scalers: dict of Scalers to use for sub-models, keyed by submodel local name

        Returns:
            None
        """
        ############################################################################################################
        ## Step 1: Scale geometric constraints
        ############################################################################################################
        self.scale_constraint_by_component(
            model.length_eqn, model.heavy_phase.length, overwrite=overwrite
        )

        for phase in ["light", "heavy"]:
            control_volume = getattr(model, f"{phase}_phase")
            constraint = getattr(model, f"{phase}_phase_area_eqn")
            for idx, vardata in control_volume.area.items():
                self.scale_constraint_by_component(
                    constraint[idx], vardata, overwrite=overwrite
                )

        ############################################################################################################
        ## Step 2: Call control volumes' constraint scaling routines
        ############################################################################################################
        self.call_submodel_scaler_method(
            model.light_phase,
            "constraint_scaling_routine",
            submodel_scalers=submodel_scalers,
            overwrite=overwrite,
        )
        self.call_submodel_scaler_method(
            model.heavy_phase,
            "constraint_scaling_routine",
            submodel_scalers=submodel_scalers,
            overwrite=overwrite,
        )
        ############################################################################################################
        ## Step 2.5: Scale isothermal constraints (TODO: move into a scaler for the ControlVolume1DExtended)
        ############################################################################################################
        if hasattr(model.light_phase, "isothermal_constraint"):
            for condata in model.light_phase.isothermal_constraint.values():
                self.scale_constraint_by_nominal_value(condata, overwrite=overwrite)

        if hasattr(model.heavy_phase, "isothermal_constraint"):
            for condata in model.heavy_phase.isothermal_constraint.values():
                self.scale_constraint_by_nominal_value(condata, overwrite=overwrite)

        ############################################################################################################
        ## Step 3: Scale performance constraints
        ############################################################################################################
        xf = model.light_phase.length_domain.last()
        for t in model.flowsheet().time:
            nom = self.get_expression_nominal_value(
                model.light_phase.properties[t, xf].flow_vol
            )
            self.set_constraint_scaling_factor(
                model.weir_flow_eqn[t], 1 / nom, overwrite=overwrite
            )


class SettlerTankInitializer(SingleControlVolumeUnitInitializer):
    """
    Initializer object for the SettlerTank unit model
    """

    def initialize_main_model(
        self,
        model: Block,
        copy_inlet_state: Bool = True,
    ):
        """
        Initialization routine for the settler tank

        Args:
            model: SettlerTank object to be initialized.
        Returns:
            Pyomo solver results object.
        """
        if model.config.dynamic:
            raise InitializationError(
                "Initialization for the SettlerTank model is supported "
                "only for steady state operation."
            )
        init_log = idaeslog.getInitLogger(
            model.name, self.get_output_level(), tag="unit"
        )
        solve_log = idaeslog.getSolveLogger(
            model.name, self.get_output_level(), tag="unit"
        )
        dof = degrees_of_freedom(model)
        if not dof == 0:
            raise InitializationError(
                "SettlerTank initialization expected 0 degrees of "
                f"freedom but instead has {dof}."
            )
        area_fixed = False
        for idx in model.light_phase.area:
            if model.light_phase.area[idx].fixed or model.heavy_phase.area[idx].fixed:
                area_fixed = True
        if area_fixed:
            raise InitializationError(
                "Initialization is not supported for streams with area fixed. "
                "Fix the settler width and exactly one phase height variable "
                "instead."
            )

        # Start by assuming that both phases take up half of the tank
        light_fixed_list = [
            vardata.fixed for vardata in model.light_phase_height.values()
        ]
        heavy_fixed_list = [
            vardata.fixed for vardata in model.heavy_phase_height.values()
        ]

        if all(light_fixed_list):
            if any(heavy_fixed_list):
                raise InitializationError(
                    "The heights of both phases cannot be fixed simultaneously."
                )
            for t in model.flowsheet().time:
                if (
                    model.light_phase_height[t].value
                    > model.light_phase_weir_height.value
                ):
                    raise InitializationError(
                        "The light phase's height is fixed to a value higher than "
                        "the light weir height, so there is no room in the settler tank "
                        "for the heavy phase. Fix either the light or heavy phase's height "
                        "to a value strictly less than the weir height."
                    )
                else:
                    for x in model.light_phase.length_domain:
                        model.light_phase.area[t, x].fix(
                            model.settler_width * model.light_phase_height[t]
                        )
                        model.heavy_phase.area[t, x].fix(
                            model.settler_width
                            * (
                                model.light_phase_weir_height
                                - model.light_phase_height[t]
                            )
                        )
        elif all(heavy_fixed_list):
            if any(light_fixed_list):
                raise InitializationError(
                    "The heights of both phases cannot be fixed simultaneously."
                )
            for t in model.flowsheet().time:
                if (
                    model.heavy_phase_height[t].value
                    > model.light_phase_weir_height.value
                ):
                    raise InitializationError(
                        "The heavy phase's height is fixed to a value higher than "
                        "the light weir height, so there is no room in the settler tank "
                        "for the light phase. Fix either the light or heavy phase's height "
                        "to a value strictly less than the weir height."
                    )
                else:
                    for x in model.heavy_phase.length_domain:
                        model.heavy_phase.area[t, x].fix(
                            model.settler_width * model.heavy_phase_height[t]
                        )
                        model.light_phase.area[t, x].fix(
                            model.settler_width
                            * (
                                model.light_phase_weir_height
                                - model.heavy_phase_height[t]
                            )
                        )
        else:
            # Neither phase's height is fixed.
            raise InitializationError(
                "Neither the height of the light phase nor the height of the "
                "heavy phase is fixed for at least one time point. Fix the "
                "height of exactly one phase."
            )

        init_log.info_high(
            "Initialization Step 1a: Initializing light phase control volume."
        )
        self.initialize_control_volume(
            model.light_phase, copy_inlet_state=copy_inlet_state
        )
        init_log.info_high(
            "Initialization Step 1b: Initializing heavy phase control volume."
        )
        self.initialize_control_volume(
            model.heavy_phase, copy_inlet_state=copy_inlet_state
        )
        init_log.info_high("Initialization Step 1 complete.")

        model.light_phase.area.unfix()
        model.heavy_phase.area.unfix()

        init_log.info_high(
            "Initialization Step 2: calculate overall liquid level from weir flow equation."
        )
        light_fixed_list = [
            vardata.fixed for vardata in model.light_phase_height.values()
        ]
        heavy_fixed_list = [
            vardata.fixed for vardata in model.heavy_phase_height.values()
        ]

        if all(light_fixed_list):
            for t in model.flowsheet().time:
                calculate_variable_from_constraint(
                    model.heavy_phase_height[t],
                    model.weir_flow_eqn[t],
                )

        elif all(heavy_fixed_list):
            for t in model.flowsheet().time:
                calculate_variable_from_constraint(
                    model.light_phase_height[t],
                    model.weir_flow_eqn[t],
                )
        else:
            raise BurntToast(
                "Exactly one phase height should be fixed at this point "
                "in initialization, but neither is fixed. Please open "
                "an issue on the PrOMMiS Github so that this error "
                "can be fixed."
            )
        init_log.info_high("Initialization Step 2 complete.")

        init_log.info_high("Initialization Step 3: Solve entire unit model.")

        solver_obj = self._get_solver()

        with idaeslog.solver_log(solve_log, idaeslog.DEBUG) as slc:
            results = solver_obj.solve(model, tee=slc.tee)
        init_log.info_high(f"Initialization Step 3 {idaeslog.condition(results)}.")

        return results


Stream_Config = ConfigDict()

Stream_Config.declare(
    "property_package",
    ConfigValue(
        default=useDefault,
        domain=is_physical_parameter_block,
        description="Property package to use for given stream",
        doc="""Property parameter object used to define property calculations for given stream,
**default** - useDefault.
**Valid values:** {
**useDefault** - use default package from parent model or flowsheet,
**PhysicalParameterObject** - a PhysicalParameterBlock object.}""",
    ),
)

Stream_Config.declare(
    "property_package_args",
    ConfigDict(
        implicit=True,
        description="Dict of arguments to use for constructing property package",
        doc="""A ConfigDict with arguments to be passed to property block(s)
and used when constructing these,
**default** - None.
**Valid values:** {
see property package for documentation.}""",
    ),
)


Stream_Config.declare(
    "energy_balance_type",
    ConfigValue(
        default=EnergyBalanceType.none,
        domain=In(
            [
                EnergyBalanceType.none,
                EnergyBalanceType.enthalpyTotal,
                EnergyBalanceType.energyTotal,
                EnergyBalanceType.isothermal,
            ]
        ),
        doc="Bool indicating whether to include energy balance for stream. Default=False.",
    ),
)

Stream_Config.declare(
    "has_pressure_balance",
    ConfigValue(
        default=False,
        domain=Bool,
        doc="Bool indicating whether to include pressure balance for stream. Default=False.",
    ),
)


@declare_process_block_class("SettlerTank")
class SettlerTankData(UnitModelBlockData):
    default_initializer = SettlerTankInitializer
    default_scaler = SettlerTankScaler

    CONFIG = ConfigDict(implicit=False)

    CONFIG.declare(
        "has_holdup",
        ConfigValue(default=True, domain=In([True]), doc="Holdup must be included."),
    )
    CONFIG.declare(
        "dynamic",
        ConfigValue(
            default=False,
            domain=DefaultBool,
            doc="Whether model is dynamic (True) or steady state (False).",
        ),
    )
    CONFIG.declare(
        "light_phase_alias",
        ConfigValue(
            default="light",
            domain=str,
            doc="Alias to use for light phase in settler",
        ),
    )

    CONFIG.declare(
        "heavy_phase_alias",
        ConfigValue(
            default="heavy",
            domain=str,
            doc="Alias to use for heavy phase in settler",
        ),
    )

    CONFIG.declare(
        "light_phase_config",
        Stream_Config(
            description="ConfigDict for light phase",
        ),
    )

    CONFIG.declare(
        "heavy_phase_config",
        Stream_Config(
            description="ConfigDict for heavy phase",
        ),
    )

    CONFIG.declare(
        "transformation_method",
        ConfigValue(
            default=useDefault,
            description="Discretization method to use for the length domain",
        ),
    )

    CONFIG.declare(
        "transformation_scheme",
        ConfigValue(
            default=useDefault,
            description="Discretization scheme to use for the length domain",
        ),
    )

    CONFIG.declare(
        "finite_elements",
        ConfigValue(
            default=5,
            domain=int,
            description="Number of finite elements length domain",
            doc="""Number of finite elements to use when discretizing the length
            domain (default=5)""",
        ),
    )

    CONFIG.declare(
        "collocation_points",
        ConfigValue(
            default=3,
            domain=int,
            description="Number of collocation points per finite element",
            doc="""Number of collocation points to use per finite element when
            discretizing length domain (default=3)""",
        ),
    )

    def build(self):
        super().build()

        # Use light phase units for flowsheet-level variables
        self._units = (
            self.config.light_phase_config.property_package.get_metadata().get_derived_units
        )

        for stream_name in ["light_phase", "heavy_phase"]:
            stream_config = getattr(self.config, f"{stream_name}_config")

            # Create control volume
            control_volume = ExtendedControlVolume1DBlock(
                has_holdup=self.config.has_holdup,
                dynamic=self.config.dynamic,
                property_package=stream_config.property_package,
                property_package_args=stream_config.property_package_args,
                transformation_method=self.config.transformation_method,
                transformation_scheme=self.config.transformation_scheme,
                finite_elements=self.config.finite_elements,
                collocation_points=self.config.collocation_points,
                area_definition=DistributedVars.variant,
            )
            self.add_component(stream_name, control_volume)

            # Add geometry and material, energy, and pressure balance equations
            control_volume.add_geometry(
                flow_direction=FlowDirection.forward,
            )
            control_volume.add_state_blocks(
                information_flow=FlowDirection.forward, has_phase_equilibrium=False
            )
            control_volume.add_material_balances(
                balance_type=MaterialBalanceType.componentTotal,
                has_phase_equilibrium=False,
                has_mass_transfer=False,
            )
            control_volume.add_energy_balances(
                balance_type=stream_config.energy_balance_type
            )
            if stream_config.has_pressure_balance:
                control_volume.add_momentum_balance(
                    balance_type=MomentumBalanceType.momentumTotal
                )
            # Discretize length domain
            control_volume.apply_transformation()

            # Add user-specified alias for stream
            stream_alias = getattr(self.config, f"{stream_name}_alias")
            if stream_name == stream_alias:
                # Either using light_phase as the alias
                # for the light phase or heavy_phase
                # as the alias for the heavy phase
                pass

            alias_phase = f"{stream_alias}_phase"
            if hasattr(self, alias_phase):
                raise ConfigurationError(
                    f"Cannot use {alias_phase} as an alias for {stream_name}_phase. "
                    f"An object with that name already exists on {self.name}."
                )
            else:
                add_object_reference(self, alias_phase, control_volume)

            self.add_inlet_port(name=f"{stream_alias}_inlet", block=control_volume)
            self.add_outlet_port(name=f"{stream_alias}_outlet", block=control_volume)

        self._make_geometry()
        self._make_performance()

    def _make_geometry(self):
        add_object_reference(
            self, local_name="length", remote_object=self.light_phase.length
        )

        @self.Constraint(doc="Equate length of phase control volumes")
        def length_eqn(self):
            return self.light_phase.length == pyunits.convert(
                self.heavy_phase.length, to_units=self._units("length")
            )

        self.settler_width = Var(
            initialize=1,
            bounds=(0, None),
            units=self._units("length"),
            doc="Width of main settler tank",
        )
        self.light_phase_weir_channel_width = Var(
            initialize=1,
            bounds=(0, None),
            units=self._units("length"),
            doc="Width of light phase weir channel.",
        )
        self.light_phase_weir_height = Var(
            initialize=1,
            bounds=(0, None),
            units=self._units("length"),
            doc="Height of light phase weir.",
        )
        self.light_phase_height = Var(
            self.flowsheet().time,
            initialize=1,
            bounds=(0, None),
            units=self._units("length"),
            doc="Height of light phase in tank",
        )
        self.heavy_phase_height = Var(
            self.flowsheet().time,
            initialize=1,
            bounds=(0, None),
            units=self._units("length"),
            doc="Height of heavy phase in tank",
        )

        @self.Expression(self.flowsheet().time)
        def total_liquid_height(b, t):
            return b.light_phase_height[t] + b.heavy_phase_height[t]

        @self.Constraint(self.flowsheet().time, self.light_phase.length_domain)
        def light_phase_area_eqn(b, t, x):
            return b.light_phase.area[t, x] == b.light_phase_height[t] * b.settler_width

        @self.Constraint(self.flowsheet().time, self.heavy_phase.length_domain)
        def heavy_phase_area_eqn(b, t, x):
            return (
                pyunits.convert(b.heavy_phase.area[t, x], to_units=self._units("area"))
                == b.heavy_phase_height[t] * b.settler_width
            )

    def _make_performance(self):
        # Assume that the light phase exits the settler tank by
        # flowing over a weir of fixed height. We make no assumption
        # about how the heavy phase exits the tank---the user must
        # define the flow rate themselves, either by fixing it or
        # writing a constraint.

        self.weir_discharge_coefficient = Param(
            # Vanden-Broeck and Keller, Weir flows, J. Fluid Mech., 1987
            initialize=0.583,
            mutable=True,
        )
        self.weir_flow_smoothing_eps = Param(
            # Assuming length units are meters, the
            # height over the top of the weir is usually
            # on the order of millimeters. Therefore, we
            # use a epsilon several orders of magnitude
            # below that.
            initialize=1e-6 * pyunits.m,
            mutable=True,
            units=self._units("length"),
        )

        @self.Constraint(self.flowsheet().time)
        def weir_flow_eqn(b, t):
            xf = b.light_phase.length_domain.last()

            H = smooth_max(
                b.total_liquid_height[t] - b.light_phase_weir_height,
                0 * b._units("length"),
                eps=b.weir_flow_smoothing_eps,
            )
            g = pyunits.convert(
                Constants.acceleration_gravity, to_units=b._units("acceleration")
            )
            # Need to convert the light phase volumetric flowrate because, presently (3/6/26),
            # the property packages of PrOMMiS have volumetric flow rate in L/hr, but the correct
            # derived units are m^3/hr
            return pyunits.convert(
                self.light_phase.properties[t, xf].flow_vol,
                to_units=self._units("flow_vol"),
            ) == pyunits.convert(
                g**0.5
                * H**1.5
                * b.light_phase_weir_channel_width
                * b.weir_discharge_coefficient,
                to_units=self._units("flow_vol"),
            )
