[files]
extend-exclude = [
    "*.svg",
    "*.png",
    "*.json",
    ]

[default.extend-words]
# Ignore IDAES
IDAES = "IDAES"
# Atomic elements
Nd = "Nd"
[default]
extend-ignore-re = [
    # Jupyter notebooks: ignore hexadecimal values in "id" cell metadata field
    '"id": "[0-9a-f]+",'
]